#!/bin/sh -e

PATH="/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin"

CONFIG_DIR=/b-persist/config
UPGRADE_DIR=/b-persist/upgrades

case "$1" in
    mount-rw)
        umount /b-persist

        fsck_code=0
        e2fsck -y /dev/vdb3 || fsck_code=$?
        if [ $fsck_code -ge 4 ] ; then
            echo 'Filesystem on /dev/vdb3 unusable, reformatting...'
            mkfs.ext4 -q -F /dev/vdb3
        fi

        mount -o rw /b-persist
        mkdir -p $CONFIG_DIR
        chmod 0777 $CONFIG_DIR
        mkdir -p $UPGRADE_DIR
        chmod 0777 $UPGRADE_DIR
        ;;
    sync)
        rsync -ac --ignore-missing-args /persist/config/ $CONFIG_DIR
        rsync -ac --ignore-missing-args /persist/upgrades/ $UPGRADE_DIR
        ;;
    *)
        echo "Unhandled argument: [$1]"
        exit 1
        ;;
esac

exit 0
