#!/bin/sh

PATH="/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin"

case "$1" in
	start)
		mkdir -p /tmp/init
		# (DEBUG) delay system booting after platform agent is started
		echo 15 > /tmp/init/platform_agent.sleep.post
		# (DEBUG) delay declaring boot success
		echo 30 > /tmp/init/FunInit.sleep.pre
		;;
	*)
		:
		;;
esac

exit 0
