#!/bin/sh

export PATH="/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin"

case "$1" in
    start)
	cd /home/root
	./factory-mmc.sh both
	;;
    stop)
	:
	;;
    *)
	echo "Usage: do-provision start"
	exit 1
	;;
esac

exit 0
