// Source file auto generated by /Users/insop/Projects/sandbox2/FunTools/ConfigGen/utils_cfg_gen.pyc at 2018-11-27 13:47 
// DO NOT change this file

#pragma once


#include <stdbool.h>


struct HostUnitFunction_cfg {
	int nrdma;
	int nxform;
	int vs_mjr;
	int vs_mnr;
	int id_did;
	int rid;
	int cap_css;
	int cap_to;
	int vs_ter;
	int cap_cqr;
	int pasid_en;
	int nport;
	int cap_mpsmin;
	int tph_en;
	int nvi;
	int nsocket;
	int cq_msb_sticky_en;
	int cc_scc;
	int ntcp;
	int cap_ams;
	int nepcq;
	int id_vid;
	int sq_msb_sticky_en;
	int cap_mpsmax;
	int cap_mqes;
	int msix_tbl_sz;
	int cap_nssrs;
	int ats_en;
	int msix_bar;
	int pf_bar_sz;
	int exp_rom_en;
	int cc_bcc;
	int cap_dstrd;
	int neth;
	int ntestflow;
	int pri_en;
	int cc_pi;
	int nepsq;
	int vf_bar_sz;

};

extern struct HostUnitFunction_cfg HostUnitFunction[8][4][8][2];

enum HostUnit_bif_mode {
	BIF_ONE_16,
	BIF_TWO_8,
	BIF_FOUR_4,
	BIF_HYBRID,
};



struct HostUnit_cfg {
	enum HostUnit_bif_mode bif_mode;
	int ctl_en;

};

extern struct HostUnit_cfg HostUnit[8];

enum HostUnitController_mode {
	EP,
	RC,
};

enum HostUnitController_pcie_gen {
	GEN1,
	GEN2,
	GEN3,
	GEN4,
};

enum HostUnitController_pcie_width {
	x1,
	x2,
	x4,
	x8,
	x16,
};



struct HostUnitController_cfg {
	int nvf_en[8];
	enum HostUnitController_mode mode;
	enum HostUnitController_pcie_gen pcie_gen;
	int pf_en;
	enum HostUnitController_pcie_width pcie_width;

};

extern struct HostUnitController_cfg HostUnitController[8][4];



struct HostUnits_cfg {
	int hu_en;

};

extern struct HostUnits_cfg HostUnits;


