// Source file generated by ./cfg_gen.py at 2018-11-27 13:47 
// Do not change this file
// Change the hwcap files in test/Configfiles

#pragma once


enum module_status {
	MODULE_EXISTS = 0,
	MODULE_NOT_EXISTS = 1,
	FEP_ONLY_MODE = 2,
};

enum platform_sku_id {
	SKU_UNKNOWN_ID = 0,
	SKU_EMU_NET2_ID = 5,
	SKU_EMU_COMPUTE3_ID = 15,
	SKU_DV_F1_NO_HSU_SBUS = 22,
	SKU_EMU_F1_PING4_ID = 23,
	SKU_EMU_CCMUHMUD_ID = 12,
	SKU_EMU_COMPUTE1_ID = 3,
	SKU_EMU_STOR2_ID = 8,
	SKU_EMU_F1_PING_ID = 21,
	SKU_DV_F1_BOOT = 18,
	SKU_EMU_STOR1_ID = 6,
	SKU_EMU_NU_HNU_ID = 11,
	SKU_MAX_ID = 253,
	SKU_EMU_CCSBPMIO_ID = 17,
	SKU_EMU_COMPUTE_DDR_ONLY_ID = 20,
	SKU_EMU_MIPS_ID = 1,
	SKU_EMU_CCMUH_ID = 10,
	SKU_EMU_CCTOP_ID = 4,
	SKU_EMU_STOR3_ID = 19,
	SKU_EMU_F1_ID = 9,
	SKU_POSIX = 14,
	SKU_EMU_COMPUTE2_ID = 7,
	SKU_EMU_NET1_ID = 2,
	SKU_EMU_STOR_NET2_ID = 16,
	SKU_QEMU_ID = 13,
};

struct __attribute__ ((packed)) emu_mem_cfg {
	unsigned int present:1;
	unsigned int size_mb:16;
};

struct __attribute__ ((packed)) mud_cfg {
	unsigned int lite:1;
	unsigned int status:4;
	unsigned int fep0:1;
	unsigned int fep1:1;
	unsigned int size_gb:12;
};

struct __attribute__ ((packed)) top_cfg {
	unsigned int pll:1;
	unsigned int mio:1;
	unsigned int emmc:1;
	unsigned int mem_repair:1;
};

struct __attribute__ ((packed)) sbp_cfg {
	unsigned int valid:1;
	unsigned int reset_vec_overwrite:1;
	unsigned int ddr_remap:1;
};

struct __attribute__ ((packed)) muh_cfg {
	unsigned int lite:1;
	unsigned int status:4;
	unsigned int fep0:1;
	unsigned int fep1:1;
	unsigned int fep2:1;
	unsigned int fep3:1;
	unsigned int sbus:1;
	unsigned int size_gb:4;
};

struct __attribute__ ((packed)) pc_cfg {
	unsigned int status:4;
	unsigned int fep:1;
	unsigned int cfg:1;
	unsigned int le:1;
	unsigned int dma:1;
	unsigned int eqm:1;
	unsigned int jpg:1;
	unsigned int cdu:1;
	unsigned int snx:1;
	unsigned int bnm:1;
	unsigned int css:1;
	unsigned int lsnmux:1;
	unsigned int snmux:1;
	unsigned int dam:1;
	unsigned int rgx:1;
	unsigned int cmh:1;
	unsigned int zip:1;
	unsigned int bp:1;
	unsigned int axm:1;
	unsigned int ca:1;
	unsigned int mdh:1;
};

struct __attribute__ ((packed)) hnu_cfg {
	unsigned int lite:1;
	unsigned int status:4;
	unsigned int fep0:1;
	unsigned int fep1:1;
	unsigned int erp:1;
	unsigned int etp:1;
	unsigned int fpg0:1;
	unsigned int fpg1:1;
	unsigned int fpg2:1;
	unsigned int fpg3:1;
};

struct __attribute__ ((packed)) hsu_cfg {
	unsigned int lite:1;
	unsigned int status:4;
	unsigned int fep:1;
	unsigned int sbus:1;
};

struct __attribute__ ((packed)) nu_cfg {
	unsigned int lite:1;
	unsigned int status:4;
	unsigned int fep0:1;
	unsigned int fep1:1;
	unsigned int fep2:1;
	unsigned int erp:1;
	unsigned int etp:1;
	unsigned int fpg0:1;
	unsigned int fpg1:1;
	unsigned int fpg2:1;
	unsigned int fpg3:1;
	unsigned int fpg4:1;
	unsigned int fpg5:1;
	unsigned int sbus:1;
};

struct __attribute__ ((packed)) hwcap_cfg {
	struct sbp_cfg sbp;
	struct pc_cfg pc[9];
	struct top_cfg top;
	struct emu_mem_cfg emu_mem;
	struct nu_cfg nu;
	struct mud_cfg mud;
	struct hnu_cfg hnu;
	struct hsu_cfg hsu[4];
	struct muh_cfg muh;
};


extern struct hwcap_cfg hwcap[];

