#include <unistd.h>
#include <stdio.h>
#include <stdlib.h>

/*
 * Verifies a HBM dump file that has been generated by the hbmdump_test
 * app in FunOS.
 *
 * That app writes a PRBS pattern to a malloc'ed location. This checker
 * verifies that the pattern is correct over the malloc'ed location.
 *
 * The checker stops immediately on detection of the first error to avoid
 * spewing too many errors.
 */

void usage(void)
{
    fprintf(stderr,
        "usage: verify <file> <address> <size>\n"
        "    <file>      dump file path\n"
        "    <address>   physical start address of the block to verify\n"
        "    <size>      size of the block in bytes\n");
}

int main(int argc, char *argv[])
{
    char *dump_fname = NULL;
    uint64_t address = 0;  /* invalid */
    uint64_t size = 0;

    if (argc != 4) {
        usage();
        exit(1);
    }

    dump_fname = argv[1];
    address = strtoull(argv[2], NULL, 0);
    size = strtoull(argv[3], NULL, 0);

    printf("Verifying %llx bytes from address %llx in dump %s\n",
            size, address, dump_fname);

    FILE *file;
    file = fopen(dump_fname, "r");

    fseek(file, address, SEEK_SET);

    uint8_t *mem = (uint8_t *) malloc(size);
    fread(mem, 1, size, file);

    uint16_t expected = 0x1;

    for (int i = 0; i < size; i += 2) {
        uint16_t actual = mem[i] | (mem[i+1] << 8);
        
        if (expected != actual) {
            uint64_t loc = address + i;
            printf("Mismatch @ 0x%llx expected %04x got %04x\n", 
                    loc, expected, actual);
            return 1;
        }
        
        uint16_t bit = ((expected >> 14) ^ (expected >> 13)) & 1;
        expected = ((expected << 1) & 0x7fff) | bit;
    }

    printf("All bytes verified successfully\n");

    return 0;
}
