#include <errno.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <inttypes.h>
#include <unistd.h>

/*
 * Verifies a HBM dump file that has been generated by the hbmdump_test
 * app in FunOS.
 *
 * That app writes a PRBS pattern to a malloc'ed location. This checker
 * verifies that the pattern is correct over the malloc'ed location.
 *
 * If the -k option is specified, the checker ensures that the location is
 * zeroed out instead of assuming a PRBS pattern. This allows checking of
 * private key regions in the dump.
 *
 * The checker stops immediately on detection of the first error to avoid
 * spewing too many errors.
 */

void usage(void)
{
    fprintf(stderr,
        "usage: verify [-k] <file> <address> <size>\n"
        "    -k          treat address and size as a zeroed-out block\n"
        "    <file>      dump file path\n"
        "    <address>   physical start address of the block to verify\n"
        "    <size>      size of the block in bytes\n");
}

int main(int argc, char *argv[])
{
    int opt;

    char *dump_fname = NULL;
    uint64_t address = 0;  /* invalid */
    uint64_t size = 0;
    int is_key_region = 0;

    /* process the optional argument(s) first */
    while ((opt = getopt(argc, argv, "k")) != -1) {
        switch (opt) {
            case 'k':
                is_key_region = 1;
                break;
            default:
                fprintf(stderr, "Unknown option %c\n", opt);
                usage();
                exit(1);
        }
    }

    /* handle the positional arguments */
    int remaining_argc = argc - optind;
    if (remaining_argc != 3) {
        usage();
        exit(1);
    }

    dump_fname = argv[optind];
    address = strtoull(argv[optind+1], NULL, 0);
    size = strtoull(argv[optind+2], NULL, 0);

    printf("Verifying 0x%"PRIx64 "bytes at address 0x%"PRIx64 " in %s (is_key: %d)\n",
            size, address, dump_fname, is_key_region);

    FILE *file;
    file = fopen(dump_fname, "r");
    if (file == NULL) {
        fprintf(stderr, "Failed to open file %s: %s\n", 
                dump_fname, strerror(errno));
        exit(1);
    }

    fseek(file, address, SEEK_SET);

    uint8_t *mem = (uint8_t *) malloc(size);
    fread(mem, 1, size, file);

    uint16_t expected = 0x1;
    if (is_key_region) {
        expected = 0x0;
    }

    for (int i = 0; i < size; i += 2) {
        uint16_t actual = mem[i] | (mem[i+1] << 8);
        
        if (expected != actual) {
            uint64_t loc = address + i;
            printf("Mismatch @ 0x%"PRIx64 " expected %04x got %04x\n", 
                    loc, expected, actual);
            return 1;
        }

        uint16_t bit = ((expected >> 14) ^ (expected >> 13)) & 1;
        expected = ((expected << 1) & 0x7fff) | bit;
        /*
         * not strictly necessary as a prbs initial seed of 0 means it'll
         * get stuck at 0, but in case someone changes the lfsr to something
         * else....
         */
        if (is_key_region) {
            expected = 0x0;
        }
    }

    printf("All bytes verified successfully\n");

    return 0;
}
