# f1 sdk config file
description: "configuration for f1 sdk apis for posix test coverage"

common_config: common_sdk_coverage_exclude_files.yml

# which hardware target image is used for the test
targets:
  - f1

# where the test coverage report is generated
platforms:
  - posix

# exclude APIs for handling 64B Wu
exclude_api_patterns:
  - channel64
  - send64
  - continuation64
  - rid_sge_cq # SGE not in F1
  - resource_check_sge_cq_ok # SGE not in F1
  - fun_dma64_2_sge_push # SGE not in F1

# The following files are excluded from the coverage report
# because they are hw specifics or not run on POSIX environment
exclude_filenames:
  - FunOS/hw/ocm
  - FunOS/hw/csr/csr2_sim.h
  - FunOS/hw/le/hw_le_sim_csr2.h
