#!/usr/bin/env python3

#	vpcie-toy-composer -- Virtual PCIe Toy Composer
#
#	Copyright (c) 2020 Fungible, Inc.  All rights reserved.
#

# This is a very small and simple "Toy Composer" using Fungible Cluster
# Services Virtual PCIe Fabric Manager to allow Virtual PCIe Fabrics to be
# created, manipulated, deleted, examined, etc.
#
# The set of supported commands are (alias tc=vpcie-toy-composer):
#
#     tc docker start
#     tc docker stop
#       -- Start/Stop Fungible Cluster Services Docker Container.
#
#     tc ztp <DPU ccLinux> ...
#       -- Perform Zero Touch Provisioning on a new DPU ccLinux instance.
#
#     tc vsw create
#         [ --max-downport-id <n> ]
#         [ --name <name> ]
#         <vPortSpec> ...
#     tc vsw hot-plug <vPortSpec> ...
#     tc vsw hot-unplug <vPortID> ...
#     tc vsw delete <vFabricID> ...
#       -- Create/Hot Plug/Hot Unplug/Delete Virtual PCIe Fabrics.
#
#     tc vsw dpus
#     tc vsw vfabrics
#       -- List existing DPUs and Virtual PCIe Fabrics.
#
#     tc vsw dpu <DPU> ...
#     tc vsw vfabric <vFabricID> ...
#       -- Display detailed information on specified DPUs and Virtual PCIe
#       -- Fabrics.
#
#     tc vsw enumerate <PortSpec> ...
#       -- Display PCIe Fabric Enumerations of DPU PCIe Switch Down Port
#       -- (can only be used when not bound into a Virtual PCIe Fabric).
#
#     tc vsw debug <DPU>
#         [ --trace-link ]
#         [ --trace-tlp ]
#         [ --trace-s2s ]
#         [ --trace-routing ]
#       -- Display/Set DPU Virtual PCIe Debug Flags.
#
# Nomenclature:
#
#     <DPU ccLinux> -- DPU ccLinux Hostname/IP Address
#     <vPortSpec>   -- <DPU>/<Portname>/<vPortID>
#     <PortSpec>    -- <DPU>/<Portname>
#     <DPU>         -- DPU Ethernet Management Port MAC Address (or name, see
#                      CS_DPUS below)
#     <Portname>    -- DPU PCIe Controller Name
#     <vPortID>     -- The Virtual Port Number that will be bound to the
#                      (<DPU>, <Portname>).  Legal values are 0..31 for
#                      PCIe Controllers configured as Switch Down Ports,
#                      32 for PCIe Controllers configured as Switch Up Ports.
#     <vFabricID>   -- The UUID for a Virtual PCIe Fabric.
#
# Useful Environment Variables:
#
#     CS_HOST       -- The Hostname/IP Address where Fungible Cluster Services
#                      is running.
#     CS_PORT       -- The TCP Port for FCS RESTful APIs (mostly for debugging).
#     CS_DPUS       -- A JSON File containing a Dictionary of DPU Names (keys)
#                      and Ethernet Management Port MAC Addresses (values).
#
# This application uses the Fungible Cluster Services Virtual PCIe Fabric
# Manager for most of its actions.  Documentation for the vPCIeFM can be
# found in the Virtual PCIe Fabric Manager APIs document.
#

import logging
import os
import sys
import subprocess
import socket
import tempfile
import argparse
import re
import json

# Set up basic Logging ...
#
logger = logging.getLogger("cs")
logging.basicConfig(level=logging.ERROR)

# Return whether the passed string argument represents a legally formated
# Ethernet MAC Address.
#
def isethermac(s):
	# xx:xx:xx:xx:xx:xx
	mac = '([0-9a-f][0-9a-f]:){5}[0-9a-f][0-9a-f]'
	return re.search('^' + mac + '$', s) != None

# The user can specify DPUs either via their Name or Management Port Ethernet
# MAC Address.  If a Name is supplied, we need to translate that to the DPU
# MAC ddress because that's the "True Name" of the DPU according to Fungible
# Cluster Services.
#
# A DPU Name to Management Port Ethernet MAC Address table can be specified
# via a file containing a JSON { key: value } object where the keys are DPU
# Names and the values are the MAC Addresses.
#
def dpu_lookup(args, dpu):
	if not isethermac(dpu):
		if not args.cs_dpus or dpu not in args.cs_dpus:
			logger.error(
			    'Argument DPU {} not Ethernet MAC and not in '
			    'mapping table'.format(dpu))
			raise
		dpu = args.cs_dpus[dpu]
	return dpu

# Given an Ethernet MAC Address, see if there's a Name translation for it.
# If so, return the Name, otherwise, just return the original MAC Address.
#
def mac_lookup(args, mac):
	if not isethermac(mac) or not args.cs_dpus:
		return mac
	for dpu in args.cs_dpus:
		if args.cs_dpus[dpu] == mac:
			return dpu
	return mac

# ArgumentParser UUID type "conversion".  Verify that the passed string is a
# legal UUID and return the string unmodified.
#
def typeuuid(s):
	# xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
	uuid = '[0-9a-f]{8}-([0-9a-f]{4}-){3}[0-9a-f]{12}'
	if not re.search('^' + uuid + '$', s):
		logger.error('Illegal UUID Format "{}"'.format(s))
		raise
	return s

# ArgumentParser JSON File type conversion.  Loads the specified JSON File and
# returns the result as the Argument Conversion.
#
def typejsonfile(s):
	with open(s, 'r') as d:
		return json.load(d)

# ArgumentParser int type conversion which returns the int() conversion of
# the argument or None if 0 is passed in.
#
def typeintnone(s):
	val = int(s)
	if val == 0:
		return None
	return val

# ArgumentParser boolean type conversion which accepts a number of different
# forms for true/false.
#
def typeboolonoff(s):
	ls = s.casefold()
	if (ls == 'true' or ls == 'on' or ls == '1'):
		return True
	if (ls == 'false' or ls == 'off' or ls == '0'):
		return False
	logger.error('"{}" not true-false/on-off/1-0'.format(s))
	raise

# Convert a <DPU>/<Portname> Specification into (dpu, portname), with DPU
# Name translations.
#
def portspec_to_tuple(args, portspec):
	port = portspec.split('/')
	if len(port) != 2:
		logger.error('Argument {} not in "DPU/PortName" format'.format(vportspec))
		raise

	dpu = dpu_lookup(args, port[0])
	portname = port[1]

	return (dpu, portname)

# Convert a <DPU>/<Portname>/<vPortID> Specification into (dpu, portname,
# vportid), with DPU Name translations.
#
def vportspec_to_tuple(args, vportspec):
	vport = vportspec.split('/')
	if len(vport) != 3:
		logger.error('Argument {} not in "DPU/PortName/vPortID" format'.format(vportspec))
		raise

	dpu = dpu_lookup(args, vport[0])
	portname = vport[1]
	vportid = vport[2]

	if not vportid.isnumeric():
		logger.error('Argument {}, vportid "{}" not a number'.format(vportspec, vportid))
		raise

	vportid = int(vportid)
	if vportid < 0 or vportid > 32:
		logger.error('Argument {}, vportid {} out of range 0..32'.format(vportspec, vportid))
		raise

	return (dpu, portname, vportid)

# Convert a command line specification of a vFabric Port into the JSON
# specification used by the Virtual PCIe Fabric Manager:
#
#   E.g. dpu/portname/vportid gets converted into:
#       {
#           'dpu' : '<dpu>',
#           'port_name' : '<portname>',
#           'virtual_port_id' : <vportid>
#       }
#
# We also support mapping DPU Names into their Ethernet Management Port MAC
# Addresses via a DPU Name to MAC Address Dictionary
#
def vportspec_to_json(args, vportspec):
	(dpu, portname, vportid) = vportspec_to_tuple(args, vportspec)
	return { 'dpu' : dpu,
		 'port_name' : portname,
		 'virtual_port_id' : vportid }

# Construct the curl command to the API Gateway.  If --verbose or --dry-run
# were specified, then dump the command on stdout.  If --dry-run was specified
# leave it at that.  Otherwise, execute the curl command and return the
# decoded JSON result.
#
def curl_api_gateway(args, options, cmd):
	api_gateway = 'http://{}:{}/FunCC/v1/'.format(args.cs_host, args.cs_port)
	curl_cmd = 'curl --silent --user {} {} {}{}'.format(
	    args.cs_user, options, api_gateway, cmd)

	if args.verbose or args.dry_run:
		print(curl_cmd)
		if args.dry_run:
			return {}

	curl_out = subprocess.getoutput(curl_cmd)
	if curl_out == '':
		logger.error('"{}" returns nothing!'.format(curl_cmd))
		raise
	result = json.loads(curl_out)
	if args.debug:
		print('Command =', curl_cmd)
		print('Result  =', result)

	if not result['status']:
		logger.error('"{}" returns "{}"'.format(curl_cmd, result))
		raise

	return result

# Execute a command on the Fungible Cluster Services Host.
#
def ssh_cs_host(args, cmd):
	if (args.cs_host == 'localhost' or args.cs_host == '127.0.0.1'):
		cs_cmd = cmd
	else:
		cs_cmd = 'ssh localadmin@{} {}'.format(args.cs_host, cmd)

	if args.verbose or args.dry_run:
		print(cs_cmd);
		if args.dry_run:
			return

	result = os.system(cs_cmd)
	if result !=0 or args.debug:
		logger.error('"{}", result = {}'.format(cs_cmd, result))
		raise

# Execute a command on a DPU ccLinux instance.
#
def ssh_cclinux(args, cclinux, cmd):
	# We use -o StrictHostKeyChecking=off to prevent ssh/scp from throwing
	# a fit when new DPU ccLinux instances have different ssh keys.  This
	# also prevents them from asking if we "really" want to trust the
	# remote Host, etc.  This is typically only an issue in testing
	# environments where DPUs are repeatedly reinstantiated and thus
	# get new keys.
	#
	cc_cmd = 'ssh -o StrictHostKeyChecking=off root@{} {}'.format(
	    cclinux, cmd)

	if args.verbose or args.dry_run:
		print(cc_cmd)
		if args.dry_run:
			return

	result = os.system(cc_cmd)
	if result != 0 or args.debug:
		logger.error('"{}", result = {}'.format(cc_cmd, result))
		raise

# Execute an scp command copying a local file to a DPU ccLinux instance remote
# file.
#
def scp_cclinux(args, cclinux, local_file, remote_file):
	# We use -o StrictHostKeyChecking=off to prevent ssh/scp from throwing
	# a fit when new DPU ccLinux instances have different ssh keys.  This
	# also prevents them from asking if we "really" want to trust the
	# remote Host, etc.  This is typically only an issue in testing
	# environments where DPUs are repeatedly reinstantiated and thus
	# get new keys.
	#
	scp_cmd = 'scp -o StrictHostKeyChecking=off {} root@{}:{}'.format(
	    local_file, cclinux, remote_file)

	if args.verbose or args.dry_run:
		print(scp_cmd)
		if args.dry_run:
			return

	result = os.system(scp_cmd)
	if result != 0 or args.debug:
		logger.error('"{}", result = {}'.format(scp_cmd, result))
		raise

# Implement Fungible Cluster Services Docker Start command:
#
#     tc docker start
#
def subcmd_docker_start(args):
	ssh_cs_host(args, 'sudo /opt/fungible/fc/etc/fun_containers.sh start')

# Implement Fungible Cluster Services Docker Stop command:
#
#     tc docker stop
#
def subcmd_docker_stop(args):
	ssh_cs_host(args, 'sudo /opt/fungible/fc/etc/fun_containers.sh clean')

# Implement DPU Zero Touch Provisioning command:
#
#     tc ztp <DPU ccLinux> ...
#
def subcmd_ztp(args):
	# Note: I tried doing this without a temporary file, but trying to
	# get the quoting right wich ssh was just too messy.
	#
	ztp_file = tempfile.NamedTemporaryFile()
	ztp_file.write(json.dumps(
	    {
		 'mgmtif' : 'eth0',
		 'controllers' : socket.gethostbyname(args.cs_host)
	    }).encode('utf-8'))
	ztp_file.write(b'\n')
	ztp_file.flush()

	for dpu in args.dpus:
		print('ZTP {} ...'.format(dpu))
		ssh_cclinux(args, dpu, 'mkdir -p /persist/config/ztp')
		scp_cclinux(args, dpu,
		    ztp_file.name, '/persist/config/ztp/startup_cfg.json')

	ztp_file.close()

# Implement Virtual PCIe Fabric Manager Create vFabric command:
#
#     tc vsw create
#         [ --max-downport-id <n> ]
#         [ --name <name> ]
#         <vPortSpec> ...
#
def subcmd_vsw_create(args):
	# Construct optional parameters ...
	#
	params = {}
	if args.down_port_id_max:
		params['down_port_id_max'] = args.down_port_id_max
	if args.name:
		params['name'] = args.name

	# Construct ports ...
	#
	ports = []
	for vportspec in args.vportspecs:
		ports.append(vportspec_to_json(args, vportspec))

	# Put these together into the Create Virtual PCIe Fabric coammand.
	#
	create = {}
	if params != {}:
		create['params'] = params
	create['ports'] = ports

	# Get everything together in the POST Data and send the command off ...
	#
	options = '--header \'Content-Type: application/json\' --data \'{}\''.format(
	    json.dumps(create))
	curl_api_gateway(args, options, 'virtual-fabrics')

# Implement Virtual PCIe Fabric Manager Hot-Plug command:
#
#     tc vsw hot-plug <vPortSpec> ...
#
def subcmd_vsw_hot_plug(args):
	ports = []
	for vportspec in args.vportspecs:
		ports.append(vportspec_to_json(args, vportspec))

	hot_plug = {}
	hot_plug['virtual_fabric'] = args.vfabric
	hot_plug['ports'] = ports

	options = '-X PATCH --header \'Content-Type: application/json\' --data \'{}\''.format(
	    json.dumps(hot_plug))
	curl_api_gateway(args, options, 'virtual-fabrics/add')

# Implement Virtual PCIe Fabric Manager Hot-Unplug command:
#
#     tc vsw hot-unplug <vPortID> ...
#
def subcmd_vsw_hot_unplug(args):
	ports = []
	for vportid in args.vportids:
		ports.append({ 'virtual_port_id' : vportid })

	hot_unplug = {}
	hot_unplug['virtual_fabric'] = args.vfabric
	hot_unplug['ports'] = ports

	options = '-X PATCH --header \'Content-Type: application/json\' --data \'{}\''.format(
	    json.dumps(hot_unplug))
	curl_api_gateway(args, options, 'virtual-fabrics/remove')

# Implement Virtual PCIe Fabric Manager Delete vFabric command:
#
#     tc vsw delete <vFabricID> ...
#
def subcmd_vsw_delete(args):
	for vfabric in args.vfabrics:
		curl_api_gateway(args, '-X DELETE',
		    'virtual-fabrics/' + vfabric)

# Implement Virtual PCIe Fabric Manager List DPUs command:
#
#     tc vsw dpus
#
def subcmd_vsw_dpus(args):
	result = curl_api_gateway(args, '', 'dpu-resources')
	dpus = result['dpus']
	if dpus == None:
		print('No DPUs online')
		return

	# If any of the DPUs returned are in our Name:MAC Table, add their
	# Names into the result.
	#
	for dpu in dpus:
		mac = dpu['dpu']
		name = mac_lookup(args, mac)
		if mac != name:
			dpu['dpu_name'] = name

	print(json.dumps(dpus, indent=args.indent, sort_keys=True))

# Implement Virtual PCIe Fabric Manager List vFabrics command:
#
#     tc vsw vfabrics
#
def subcmd_vsw_vfabrics(args):
	result = curl_api_gateway(args, '', 'virtual-fabrics')
	vfabrics = result['virtual_fabrics']
	if vfabrics == None:
		print('No vfabrics present')
		return

	print(json.dumps(vfabrics, indent=args.indent, sort_keys=True))

# Implement Virtual PCIe Fabric Manager List DPU PCIe Ports command:
#
#     tc vsw dpu <DPU> ...
#
def subcmd_vsw_dpu(args):
	for dpu in args.dpus:
		result = curl_api_gateway(args, '',
		    'dpu-resources/' + dpu_lookup(args, dpu) + '/pcie-ports')
		print(mac_lookup(args, dpu), ':',
		    json.dumps(result['ports'], indent=args.indent,
			sort_keys=True))

# Implement Virtual PCIe Fabric Manager List vFabric Ports command:
#
#     tc vsw vfabric <vFabricID> ...
#
def subcmd_vsw_vfabric(args):
	for vfabric in args.vfabrics:
		result = curl_api_gateway(args, '',
		    'virtual-fabrics/' + vfabric + '/ports')

		# If any of the DPUs returned are in our Name:MAC Table, add
		# their Names into the result.
		#
		for port in result['ports']:
			mac = port['dpu']
			name = mac_lookup(args, mac)
			if mac != name:
				port['dpu_name'] = name

		print(vfabric, ':',
		    json.dumps(result, indent=args.indent, sort_keys=True))

# Implement Virtual PCIe Fabric Manager DU/Portname Enumeration command:
#
#     tc vsw enumerate <DPUPortSpec> ...
#
def subcmd_vsw_enumerate(args):
	for portspec in args.portspecs:
		(dpu, portname) = portspec_to_tuple(args, portspec)
		result = curl_api_gateway(args, '',
		    '/dpu-resources/' + dpu + '/pcie-ports/' + portname)
		print(portspec, ':',
		    json.dumps(result['enumeration'],
			 indent=args.indent, sort_keys=True))

# Implement Virtual PCIe Fabric Manager DPU Debug options
#
#     tc vsw debug <DPU>
#         [ --trace-link ]
#         [ --trace-tlp ]
#         [ --trace-s2s ]
#         [ --trace-routing ]
#
def subcmd_vsw_debug(args):
	# There's probably an easier wat to get ArgumentParser to leave a flag
	# if any of the Set Debug Options have been used.  But for now we'll
	# just check them manually ...
	#
	set_options = (
	    args.trace_link    != None or
	    args.trace_tlp     != None or
	    args.trace_s2s     != None or
	    args.trace_routing != None)

	dpu = dpu_lookup(args, args.dpu)
	cmd = 'dpu-resources/{}/debug-flags'.format(dpu)

	result = curl_api_gateway(args, '', cmd)

	# If no Set Debug Options were present, then we can just dump out the
	# current DPU Debug Flags and return.
	#
	if not set_options:
		print(json.dumps(result, indent=args.indent))
		return

	# Annoyingly, the Virtual PCIe Fabric Manager insists that we supply
	# all of the DPU Trace Flags, even if we only want to change a subset.
	# Se wee need to merge our new selections into the old set.
	#
	new_debug = result
	if not args.dry_run:
		new_debug.pop('status')

	if args.trace_link != None:
		new_debug['trace_link'] = args.trace_link
	if args.trace_tlp != None:
		new_debug['trace_tlp'] = args.trace_tlp
	if args.trace_s2s != None:
		new_debug['trace_s2s'] = args.trace_s2s
	if args.trace_routing != None:
		new_debug['trace_routing'] = args.trace_routing

	# Note that we need to single-quote the JSON since it will use
	# double-quotes ...
	#
	options = '--header \'Content-Type: application/json\' --data \'{}\''.format(
	    json.dumps(new_debug))
	curl_api_gateway(args, options, cmd)

def main():
	# The vast majority of the work for main() is done in the Argument
	# Parser ...
	#
	cmd_parser = argparse.ArgumentParser(
	    description="Fungible Cluster Services Client Application")

	# Arguments for all sub-functions:
	#
	cmd_parser.add_argument('-c', '--cs-host',
	    type=str,
	    default=os.environ.get('CS_HOST', 'localhost'),
	    help='Fungible Cluster Services Host [env: CS_HOST]')
	cmd_parser.add_argument('-p', '--cs-port',
	    type=int,
	    default=os.environ.get('CS_PORT', 50220),
	    help='TCP Port for Fungible Cluster Services [env: CS_PORT]')
	cmd_parser.add_argument('-u', '--cs-user',
	    type=str,
	    default=os.environ.get('CS_USER', 'admin:password'),
	    help='User:Password for accessing Fungible Cluster Services [env: CS_USER]')
	cmd_parser.add_argument('-d', '--cs-dpus',
	    type=typejsonfile,
	    default=os.environ.get('CS_DPUS', None),
	    help='JSON File mapping DPU Names to MAC Addresses [env: CS_DPUS]')

	cmd_parser.add_argument('-I', '--indent',
	    type=typeintnone, default=4,
	    help='Pretty printing indentation, default 4, 0 means none')
	cmd_parser.add_argument('-v', '--verbose',
	    action='store_true',
	    help='Display verbose output')
	cmd_parser.add_argument('-n', '--dry-run',
	    action='store_true',
	    help='Just display commands which would have been executed')
	cmd_parser.add_argument('-D', '--debug',
	    action='store_true',
	    help='Debug {} ...'.format(os.path.basename(sys.argv[0])))

	# Add sub-parsers for various sub-commands:
	#
	subcmd_parsers = cmd_parser.add_subparsers()

	# Fungible Cluster Services Docker utility commands.
	#
	#     tc docker start
	#     tc docker stop
	#
	subcmd_docker_parser = subcmd_parsers.add_parser('docker',
	    description='Fungible Cluster Services Docker utility commands')
	subcmd_docker_parsers = subcmd_docker_parser.add_subparsers()

	subcmd_docker_start_parser = subcmd_docker_parsers.add_parser(
	    'start',
	    description='Start Fungible Cluster Services Docker Container')
	subcmd_docker_start_parser.set_defaults(func=subcmd_docker_start)

	subcmd_docker_stop_parser = subcmd_docker_parsers.add_parser(
	    'stop',
	    description='Stop Fungible Cluster Services Docker Container')
	subcmd_docker_stop_parser.set_defaults(func=subcmd_docker_stop)

	# Zero Touch Provisioning commands.
	#
	#     tc ztp <DPU ccLinux> ...
	#
	subcmd_ztp_parser = subcmd_parsers.add_parser('ztp',
	    description='Zero Touch Provisioning for specified DPUs')
	subcmd_ztp_parser.add_argument(
	    'dpus', nargs='+',
	    help='One or more DPU ccLinuxes to Provision')
	subcmd_ztp_parser.set_defaults(func=subcmd_ztp)

	# Virtual PCIe Fabric Manager commands.
	#
	subcmd_vsw_parser = subcmd_parsers.add_parser('vsw',
	    description='Virtual PCIe Fabric Manager commands')
	subcmd_vsw_parsers = subcmd_vsw_parser.add_subparsers()

	# tc vsw create
	#     [ --max-downport-id <n> ]
	#     [ --name <name> ]
	#     <vPortSpec> ...
	#
	subcmd_vsw_create_parser = subcmd_vsw_parsers.add_parser(
	    'create',
	    description='Create Virtual PCIe Fabric')
	subcmd_vsw_create_parser.add_argument(
	    '-M', '--down-port-id-max',
	    type=int,
	    help='Maximum Switch Down Port ID 0..31')
	subcmd_vsw_create_parser.add_argument(
	    '-N', '--name',
	    help='Opaque "name" of Virtual PCIe Fabric')
	subcmd_vsw_create_parser.add_argument(
	    'vportspecs', nargs='+',
	    help='Virtual PCIe Ports in the format "DPU/Portname/vPortID"')
	subcmd_vsw_create_parser.set_defaults(func=subcmd_vsw_create)

	# tc vsw hot-plug <vFabricID> <vPortSpec> ...
	#
	subcmd_vsw_hot_plug_parser = subcmd_vsw_parsers.add_parser(
	    'hot-plug',
	    description='Hot Plug new Ports into a Virtual PCIe Fabric')
	subcmd_vsw_hot_plug_parser.add_argument(
	    'vfabric', type=typeuuid,
	    help='Virtual PCIe Fabric ID (UUID) to operate on')
	subcmd_vsw_hot_plug_parser.add_argument(
	    'vportspecs', nargs='+',
	    help='Virtual PCIe Ports in the format "DPU/Portname/vPortID"')
	subcmd_vsw_hot_plug_parser.set_defaults(func=subcmd_vsw_hot_plug)

	# tc vsw hot-unplug <vFabricID> <vPortID> ...
	#
	subcmd_vsw_hot_unplug_parser = subcmd_vsw_parsers.add_parser(
	    'hot-unplug',
	    description='Hot Unplug Ports from Virtual PCIe Fabric')
	subcmd_vsw_hot_unplug_parser.add_argument(
	    'vfabric', type=typeuuid,
	    help='Virtual PCIe Fabric ID (UUID) to operate on')
	subcmd_vsw_hot_unplug_parser.add_argument(
	    'vportids', nargs='+', type=int,
	    help='Virtual PCIe Port IDs in the format "vPortID"')
	subcmd_vsw_hot_unplug_parser.set_defaults(func=subcmd_vsw_hot_unplug)

	# tc vsw delete <vFabricID> ...
	#
	subcmd_vsw_delete_parser = subcmd_vsw_parsers.add_parser(
	    'delete',
	    description='Delete Virtual PCIe Fabric')
	subcmd_vsw_delete_parser.add_argument(
	    'vfabrics', nargs='+', type=typeuuid,
	    help='Virtual PCIe Fabric ID (UUID) to operate on')
	subcmd_vsw_delete_parser.set_defaults(func=subcmd_vsw_delete)

	# tc vsw dpus
	#
	subcmd_vsw_dpus_parser = subcmd_vsw_parsers.add_parser(
	    'dpus',
	    description='List DPUs')
	subcmd_vsw_dpus_parser.set_defaults(func=subcmd_vsw_dpus)

	# tc vsw vfabrics
	#
	subcmd_vsw_vfabrics_parser = subcmd_vsw_parsers.add_parser(
	    'vfabrics',
	    description='List Virtual PCIe Fabrics')
	subcmd_vsw_vfabrics_parser.set_defaults(func=subcmd_vsw_vfabrics)

	# tc vsw dpu <DPU> ...
	#
	subcmd_vsw_dpu_parser = subcmd_vsw_parsers.add_parser(
	    'dpu',
	    description='List DPU PCIe Ports')
	subcmd_vsw_dpu_parser.add_argument(
	    'dpus', nargs='+',
	    help='DPUs to list Hardware PCIe Ports')
	subcmd_vsw_dpu_parser.set_defaults(func=subcmd_vsw_dpu)

	# tc vsw vfabric <vFabricID> ...
	#
	subcmd_vsw_vfabric_parser = subcmd_vsw_parsers.add_parser(
	    'vfabric',
	    description='List Virtual PCIe Fabric Ports')
	subcmd_vsw_vfabric_parser.add_argument(
	    'vfabrics', nargs='+', type=typeuuid,
	    help='Virtual PCIe Fabrics to list Virtual PCIe Ports')
	subcmd_vsw_vfabric_parser.set_defaults(func=subcmd_vsw_vfabric)

	# tc vsw enumerate <PortSpec> ...
	#
	subcmd_vsw_enumerate_parse = subcmd_vsw_parsers.add_parser(
	    'enumerate',
	    description='Display DPU PCIe Switch Down Port Enumeration')
	subcmd_vsw_enumerate_parse.add_argument(
	    'portspecs', nargs='+',
	    help='DPU Switch Down Ports in the format "DPU/Portname"')
	subcmd_vsw_enumerate_parse.set_defaults(func=subcmd_vsw_enumerate)

	# tc vsw debug <DPU>
	#     [ --trace-link ]
	#     [ --trace-tlp ]
	#     [ --trace-s2s ]
	#     [ --trace-routing ]
	#
	subcmd_vsw_debug_parser = subcmd_vsw_parsers.add_parser(
	    'debug',
	    description='Manage DPU vSwitch Debug options')
	subcmd_vsw_debug_parser.add_argument(
	    'dpu',
	    help='DPU to operate on')
	subcmd_vsw_debug_parser.add_argument(
	    '--trace-link',
	    type=typeboolonoff,
	    help='Trace PCIe Link Events')
	subcmd_vsw_debug_parser.add_argument(
	    '--trace-tlp',
	    type=typeboolonoff,
	    help='Trace PCIe Transaction Layer Packets')
	subcmd_vsw_debug_parser.add_argument(
	    '--trace-s2s',
	    type=typeboolonoff,
	    help='Trace Switch-to-Switch Messages')
	subcmd_vsw_debug_parser.add_argument(
	    '--trace-routing',
	    type=typeboolonoff,
	    help='Trace PCIe Routing Changes')
	subcmd_vsw_debug_parser.set_defaults(func=subcmd_vsw_debug)


	# Parse the arguments and execute the indicated sub-command ...
	#
	try:
		args = cmd_parser.parse_args()
	except:
		logger.error('Failed to parse command line')
		exit(1)

	if args.debug:
		print('args =', args)

	if 'func' not in args:
		logger.error('Parser failed to return Command Function: '
		    'args =', args)
		exit(1)

#	try:
	args.func(args)
#	except:
#		logger.error('Failed to execute command')
#		exit(1)

if __name__ == "__main__":
	main()
