#!/usr/bin/python
# -*- coding: utf-8 -*-
"""
Convert FunOS timestamps from epoch to Linux syslog style:

% funos_timstamp.py [-o output] [input]
"""

from __future__ import print_function
import argparse
import datetime as d, re, sys

class TSConverter:
    """
    Given output from FunOS, convert timestamps. For example:

    1606763826.634203 => Nov 30 11:17:06.634203

    Methods
    -------
    fix_line(line):
        Fix the timestamp for the provided line.
    fix_file(infile, outfile):
        Given open file handles, infile and outfile, fix the timestamps on
        lines in infile, and write to outfile.
    """

    def __init__(self):
        # 3 match groups, before the timestamp, the timestamp, and after the
        # timestamp. Only match timestamps starting with 9 digits, this avoids
        # converting the timestamps at the beginning of FunOS logs before they
        # have established an initial time reference.
        self.matcher = re.compile("^(.*\[)(\d{9,}\.\d+)( \d.\d.\d\])")

    @staticmethod
    def _fix_match(match):
        before, ts_str, after = match.groups()
        ts = float(ts_str)

        converted = d.datetime.fromtimestamp(ts).strftime("%b %d %H:%M:%S.%f")

        return "{}{}{}".format(before, converted, after)

    def fix_line(self, line):
        """
        Fix the timestamp for the provided line.
        """

        return self.matcher.sub(TSConverter._fix_match, line)

    def fix_file(self, infile, outfile):
        """
        Given open file handles, infile and outfile, fix the timestamps on
        lines in infile, and write to outfile.
        """

        for line in infile:
            outfile.write(self.fix_line(line))

###
##  work out input and output
#
def main():

    parser = argparse.ArgumentParser()
    parser.add_argument("-o", "--output", action="store", default="-")
    parser.add_argument("input", nargs='?', action="store", default="-")

    args = parser.parse_args()

    if (args.input == "-"):
        infl = sys.stdin
    else:
        infl = open(args.input, "r")

    if (args.output == "-"):
        outfl = sys.stdout
    else:
        outfl = open(args.output, "w")

    converter = TSConverter()
    converter.fix_file(infl, outfl)
        
    
###
##  entrypoint
#
if (__name__ == "__main__"):
    main()
