general:
  debug: False
  debug_log: False

extra:
  notif_suffix: "**"
chart:
  notification: red
  module: blue

file_names:
  input_modules_init: modules.json
  input_notifications_init: notifications.json
  output_sorted_df: fun_module_init_df_sorted
  output_full_chart: fun_module_init_chart
  output_full_module_notif_chart: fun_module_notif_init_chart
  output_collapsed_chart: fun_module_init_df_collapsed
  output_collapsed_module_notif_chart: fun_module_notif_init_df_collapsed