general:
  debug: False
  debug_log: False

file_names:
  input_modules_init: modules.json
  output_sorted_df: fun_module_init_df_sorted
  output_full_chart: fun_module_init_chart
  output_collapsed_chart: fun_module_init_df_collapsed