#include "Headers.hpp"

unordered_map<string, OpClass> OpType::op_map = {
{ "b", BranchDelay},
{ "bc1eqz", BranchDelay},
{ "bc1nez", BranchDelay},
{ "beq", BranchDelay},
{ "beqz", BranchDelay},
{ "bgez", BranchDelay},
{ "bgtz", BranchDelay},
{ "blez", BranchDelay},
{ "bltz", BranchDelay},
{ "bne", BranchDelay},
{ "bnez", BranchDelay},
{ "jr", BranchDelay},
{ "jr.hb", BranchDelay},
{ "j", BranchDelay},
{ "jalr", BranchDelay},

{ "balc", BranchCompact},
{ "bc", BranchCompact},
{ "beqc", BranchCompact},
{ "beqzc", BranchCompact},
{ "bgec", BranchCompact},
{ "bgeuc", BranchCompact},
{ "bgezc", BranchCompact},
{ "bgtzc", BranchCompact},
{ "blezc", BranchCompact},
{ "bltc", BranchCompact},
{ "bltuc", BranchCompact},
{ "bltzc", BranchCompact},
{ "bnec", BranchCompact},
{ "bnezc", BranchCompact},

{ "eret", BranchCompact},

{ "jalrc", BranchCompact},
{ "jrc", BranchCompact},

{ "add", Regular },
{ "add.d", Regular },
{ "add.s", Regular },
{ "addiu", Regular },
{ "addu", Regular },
{ "and", Regular },
{ "andi", Regular },
{ "cache", Regular },
{ "clz", Regular },
{ "cmp.eq.d", Regular },
{ "cmp.le.d", Regular },
{ "cmp.lt.d", Regular },
{ "cmp.or.d", Regular },
{ "cmp.une.d", Regular },
{ "cvt.d.l", Regular },
{ "cvt.d.s", Regular },
{ "cvt.d.w", Regular },
{ "cvt.s.l", Regular },
{ "daddiu", Regular },
{ "daddu", Regular },
{ "dclz", Regular },
{ "ddiv", Regular },
{ "ddivu", Regular },
{ "dext", Regular },
{ "dins", Regular },
{ "div", Regular },
{ "div.d", Regular },
{ "div.s", Regular },
{ "divu", Regular },
{ "dlsa", Regular },
{ "dmfc0", Regular },
{ "dmfc1", Regular },
{ "dmfgc0", Regular },
{ "dmod", Regular },
{ "dmodu", Regular },
{ "dmtc0", Regular },
{ "dmtc1", Regular },
{ "dmtgc0", Regular },
{ "dmuh", Regular },
{ "dmuhu", Regular },
{ "dmul", Regular },
{ "dnegu", Regular },
{ "dror", Regular },
{ "dror32", Regular },
{ "dsbh", Regular },
{ "dshd", Regular },
{ "dsll", Regular },
{ "dsll32", Regular },
{ "dsllv", Regular },
{ "dsra", Regular },
{ "dsra32", Regular },
{ "dsrl", Regular },
{ "dsrl32", Regular },
{ "dsrlv", Regular },
{ "dsubu", Regular },
{ "ehb", Regular },
{ "ext", Regular },
{ "ins", Regular },
{ "lapc", Regular },
{ "lb", Regular },
{ "lbu", Regular },
{ "ld", Regular },
{ "ldc1", Regular },
{ "lh", Regular },
{ "lhu", Regular },
{ "li", Regular },
{ "ll", Regular },
{ "lld", Regular },
{ "lsa", Regular },
{ "lui", Regular },
{ "lw", Regular },
{ "lwc1", Regular },
{ "lwu", Regular },
{ "mfc0", Regular },
{ "mfc1", Regular },
{ "mod", Regular },
{ "modu", Regular },
{ "mov.d", Regular },
{ "move", Regular },
{ "mtc0", Regular },
{ "muh", Regular },
{ "muhu", Regular },
{ "mul", Regular },
{ "mul.d", Regular },
{ "neg.d", Regular },
{ "negu", Regular },
{ "nop", Regular },
{ "nor", Regular },
{ "or", Regular },
{ "ori", Regular },
{ "pref", Regular },
{ "ror", Regular },
{ "sb", Regular },
{ "sc", Regular },
{ "scd", Regular },
{ "sd", Regular },
{ "sdbbp", Regular },
{ "sdc1", Regular },
{ "seb", Regular },
{ "seh", Regular },
{ "seleqz", Regular },
{ "selnez", Regular },
{ "sh", Regular },
{ "sll", Regular },
{ "sllv", Regular },
{ "slt", Regular },
{ "slti", Regular },
{ "sltiu", Regular },
{ "sltu", Regular },
{ "sra", Regular },
{ "srav", Regular },
{ "srl", Regular },
{ "srlv", Regular },
{ "sub.d", Regular },
{ "subu", Regular },
{ "sw", Regular },
{ "swc1", Regular },
{ "sync", Regular },
{ "sync_mb", Regular },
{ "sync_rmb", Regular },
{ "teq", Regular },
{ "tlbgr", Regular },
{ "tlbgwi", Regular },
{ "tlbinvf", Regular },
{ "tlbr", Regular },
{ "tlbwi", Regular },
{ "tlbwr", Regular },
{ "trunc.l.d", Regular },
{ "trunc.w.d", Regular },
{ "wait", Regular },
{ "wrpgpr", Regular },
{ "wsbh", Regular },
{ "xor", Regular },
{ "xori", Regular },

};
