#!/usr/bin/env bash
#
# Generate the PFX for ESRP Client Authentication
#
# The "PKCS7" file retrieve from the ESRP portal and the
# key generated by the script gen_esrp_csr.sh are combined
# to create a PFX suitable for ESRP client authentication
#
# Copyright (c) 2024. Microsoft Corporation
#
#

USAGE=$(cat <<-EOF
$0 <p7file> <keyfile>

Generate a PFX file for an ESRP client (esrp.pfx)

You will be prompted for the password for the key file
and then for the password to protect the generated PFX file
EOF
)

if [ "$#" -ne 2 ]; then
   echo "$USAGE" >&2
   exit 1
fi


tmpfile=$(mktemp /tmp/esrp_XXXXXX.p7b)

echo "-----BEGIN PKCS7-----" > ${tmpfile}
cat "$1" >> ${tmpfile}
echo "-----END PKCS7-----" >> ${tmpfile}

openssl pkcs7 -print_certs -in ${tmpfile} -out esrp_all_certs.der

rm ${tmpfile}

openssl pkcs12 -export -in esrp_all_certs.der -inkey "$2" -out esrp.pfx
