#!/bin/bash

gen_hdr() {
	cat << EOF > $1
/*
 *      MCTP Daemon - FC mctp configuration
 *      Copyright © 2021 Fungible. All rights reserved.
 *
 *      autogenerated by ${0##*/} - DO NOT EDIT
 */
EOF
}

addline() {
	echo "$1" >> $path/$dest
}

while [ "$#" -gt 0 ]; do
	case "$1" in
	-p | --path) path="$2"
		shift;;

	*) dir $"Unknown option $1"
		;;
	esac
	shift
done

: ${MCTP_CONFIG=./.config}
: ${dest=auto_conf.h}
: ${path=./}

[ ! -f $MCTP_CONFIG ] && exit 2
(> $path/$dest)

gen_hdr $path/$dest
addline "#ifndef _INC_AUTO_CONF_HDR_"
addline "#define _INC_AUTO_CONF_HDR_"
addline ""

skip="#;"

while read line; do
	[ -z "$line" ] && continue
	[[ $line =~ ^["$skip"] ]] && continue
	echo "$line" | grep -i "is not set" >&/dev/null && continue

	IFS="=" read -a conf <<< "$line"
	[ "${conf[1]}" != "y" ] && continue
	addline "#define ${conf[0]}"
done < $MCTP_CONFIG

addline ""
addline "#endif /* _INC_AUTO_CONF_HDR_ */"
