#!/usr/bin/env python3
#
#  dpc_cli
#
#  Created by rushikesh.pendse@fungible.com on 2018-05-29
#
#  Copyright 2018 Fungible Inc. All rights reserved.
#

import sys
import imp
import os

## Add import paths so we can run in place
scriptroot = os.path.dirname(os.path.abspath(__file__))
sys.path.append(scriptroot)
sys.path.append(os.path.join(scriptroot, "src"))
sys.path.append(os.path.join(scriptroot, "src/dpcsh_interactive_client"))

from dpcsh_interactive_client.cmd_controller import CmdController

INTRO = """
    Interactive Client over DPC 
    Features :-
    1. Set/Get configs 
    2. Clear Stats
    3. Peek various Stats in iterations at certain time interval. Shows difference in counters in tabular format. 
       Also user can grep specific counters by using regex
    4. Capture stats to a file. You can provide a filename or it will create a file and print it on console once 
       command is executed successfully.
    
    For "help" or "-h" for available commands/sub-commands
"""


def main():
    try:
        ip_address = input("Enter DPC server IP (Default 10.1.21.120): ")
        tcp_port_num = input("Enter Port num on which DPC is listening (Default 43101): ")
        if not ip_address:
            ip_address = "10.1.21.120"
        if not tcp_port_num:
            tcp_port_num = 43101

        cmd_controller_obj = CmdController(target_ip=ip_address, target_port=int(tcp_port_num), verbose=False)
        cmd_controller_obj.cmdloop(intro=INTRO)
    except Exception as ex:
        print(ex)
        sys.exit(1)


if __name__ == '__main__':
    main()




